= REPL Options
David Nolen
2016-07-29
:type: reference
:toc: macro
:icons: font

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

ClojureScript REPLs can take nearly all the same options that can be
supplied to `cljs.closure/build`, for details see <<compiler-options#,Compiler Options>>.
This page documents additional supported options.

Note that options presented below under General Options should be passed
as compiler options (via `-co` / `--compile-opts` if using `cljs.main`), while
REPL-environment-specific options should be passed as REPL options
(via `-ro` / `repl-opts` if using `cljs.main`).

== General Options

[[analyze-path]]
=== :analyze-path

Sets a source path to analyze upon REPL initialization so that, if it
connects to an already-running JavaScript environment, symbols for any
previously loaded namespaces are available. May also be set to a vector
of paths to analyze.

[source,clojure]
----
:analyze-path "src"
----

[[def-emits-var]]
=== :def-emits-var

Sets whether `def` (and derived) forms evaluated at the REPL return
either a Var (if set to `true`) or the `def` init value (if `false`).
Only affects forms evaluated at the REPL; compiled source behaves as if
set to `false`. Default is `true`.

[source,clojure]
----
:def-emits-var false
----

[[repl-requires]]
=== :repl-requires

Specifies a set of lib specs (per the `require` REPL special) to be
automatically loaded when launching a REPL. Defaults to specs that refer
`doc` _etc._ along with `pp`.

[source,clojure]
----
:repl-requires [[cljs.repl :refer-macros [source doc find-doc apropos dir pst]]
                [cljs.pprint :refer [pprint] :refer-macros [pp]]]
----

[[repl-verbose]]
=== :repl-verbose

Enable verbose reporting for the REPL. Useful for debugging. Defaults to
`false`.

[source,clojure]
----
:repl-verbose true
----

This prints the compiled JavaScript before printing its evaluation:

....
cljs.user=> (+ 1 2)
((1) + (2))
3
....

[[warn-on-undeclared]]
=== :warn-on-undeclared

Overrides warnings related to the use of undeclared vars and non-existent
namespaces at the REPL (specifically `:unprovided`, `:undeclared-var`,
`:undeclared-ns`, and `:undeclared-ns-form`). Defaults to `true`.

[source,clojure]
----
:warn-on-undeclared false
----

[[watch]]
=== :watch

Watch a source directory for recompilation to avoid spinning up an
additional JVM.

[source,clojure]
----
:watch "src"
----

[[watch-fn]]
=== :watch-fn

[source,clojure]
----
:watch-fn (fn [] (println "built!"))
----

A function of no arguments to run after a successful build.

== Browser REPL Options

These options are only applicable to the browser REPL that ships with ClojureScript.

[[launch-browser]]
=== :launch-browser

By default, starting the browser REPL launches the default browser configured with your operating system to connect back to it. You can disable this behavior by setting this option to `false`, and when doing so you will be prompted to connect with a message like

[source,shell]
----
Waiting for browser to connect to http://localhost:9000 ...
----

[source,clojure]
----
:launch-browser false
----

[[working-dir]]
=== :working-dir

The directory where the compiled REPL client JavaScript will
be stored. Defaults to ".repl" with a ClojureScript version
suffix, eg. ".repl-1.9-946".

[[static-dir]]
=== :static-dir

List of directories to search for static content. Defaults to
`["." "out/"]`.

[[src]]
=== :src
The source directory containing user-defined cljs files. Used to
support reflection. Defaults to `"src/"`.

[[port]]
=== :port
Default port is 9000. To change use `:port N` where N is the desired port number. 

== Node REPL Options

[[host]]
=== :host

The host that the Node subprocess listens on for REPL traffic.

[source,clojure]
----
:host "localhost"
----

[[port]]
=== :port

The port that the Node subprocess listens on for REPL traffic.

[source,clojure]
----
:port 49152
----

== Graal.JS REPL Options

Executing `js --help:languages` will display a list of Graal.JS-specific options.
Any REPL option with a string key starting with `"js."` will be passed through
to the Graal.JS engine. Such entries should have string values.

Here is an example enabling and using the ECMAScript Internationalization API:

----
$ clj -M -m cljs.main -re graaljs -ro '{"js.intl-402" "true"}' -r
cljs.user=> (def gas-price (js/Intl.NumberFormat. "en-US"
                             #js {:style "currency"
                                  :currency "USD"
                                  :minimumFractionDigits 3}))
#'cljs.user/gas-price
cljs.user=> (.format gas-price 5.259)
"$5.259"
----
