= Contributing to ClojureScript
Rich Hickey
2016-08-01
:type: community
:toc: macro
:icons: font

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

== Making a contribution

If you have a proposal for ClojureScript, please post it as a question on https://ask.clojure.org[https://ask.clojure.org] using the ClojureScript category and label it `request`. ClojureScript developers will help you determine whether this idea is a good fit for ClojureScript and a patch is wanted.

If the ClojureScript developers indicate this is a useful thing to do, please follow the https://clojure.org/dev/dev[process] to become a contributor. This requires signing the Contributor Agreement and requesting access to the ClojureScript jira account.

== Contributor Agreement

Following the lead of other open source projects, the ClojureScript project requires contributors to jointly assign their copyright on contributed code. The https://secure.echosign.com/public/hostedForm?formid=95YMDL576B336E[Contributor Agreement] (CA) gives Rich Hickey and the contributor joint copyright interests in the code: the contributor retains copyrights while also granting those rights to Rich Hickey as the open source project sponsor.

The CA is derived from the Oracle Contributor Agreement (OCA), used for OpenJDK, Netbeans and OpenSolaris projects and others. There is a good http://www.oracle.com/technetwork/oca-faq-405384.pdf[OCA FAQ] answering many questions.

The CA does not change the rights or responsibilities of the Clojure community under the http://opensource.org/licenses/eclipse-1.0.php[Eclipse Public License (EPL)]. By executing the CA, contributors protect the Clojure code base, enable alternative licensing models, and protect the flexibility to adapt the project to the changing demands of the community. In order for the CA to be effective, the Clojure project must obtain an assignment for all contributions. Please review the CA for a complete understanding of its terms and conditions. By contributing source code or other material to Clojure, you represent that you have a CA with Rich Hickey for such contributions. In order to track contributors, you understand that your full name and username may be posted on a web page listing authorized contributors that is accessible via a public URL.

== Instructions for submitting the agreement

* Fill out and submit the https://secure.echosign.com/public/hostedForm?formid=95YMDL576B336E[Contributor Agreement] (an online e-form)

Please see the https://clojure.org/community/contributing[Contributing] page for a collection of resources on tickets, builds, patches, source, and more. If you'd like to submit a patch, please follow these guidelines on the https://clojure.org/community/workflow[preferred process for submitting].

_**Many thanks for your contributions to ClojureScript!**_
