= Reporting Issues
David Nolen
2016-08-01
:type: community
:toc: macro
:icons: font

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

It's important that before submitting any issue that you have a thorough
understanding of the <<xref/../../../guides/quick-start#,Quick Start>> first. Even if you are an
experienced ClojureScript developer this is required reading.

It's helpful, but not essential, to first check the
http://dev.clojure.org/jira/browse/CLJS[existing bug reports], the
https://groups.google.com/forum/#!forum/clojurescript[mailing list], or
the Freenode #clojurescript IRC channel or Slack channels and ensure
that the issue hasn't been reported before.

Also, it can be helpful to ensure that you are running the latest
released version of ClojureScript. Also, checking against ClojureScript
master is prudent—frequently when bugs are found, fixes are quickly
committed (see instructions below).

It is essential, however, to report the bug using ClojureScript only.
Downstream tooling often interacts with the ClojureScript compiler in
non-trivial ways, and the best way to isolate the issue to ClojureScript
is to remove them from the report altogether.

Please report issues by building the uberjar from master and using this
to verify the issue. Do not use any other 3rd party tooling (Maven,
Leiningen, Boot). When creating issues please add all relevant
instructions and code to reproduce to the ticket directly or via
additional comments. Please do not attach projects, links to projects,
links to gists / pastebins, or zips.

[NOTE]
====
Bootstrap issues may require special consideration. Please see <<reporting-bootstrap-issues#,Reporting Bootstrap Issues>> for more details.
====

[[building-the-uberjar-from-master]]
=== Building the uberjar from master

Make a checkout of the ClojureScript repository. From the root of the
project run the following:

[source,bash]
----
./script/uberjar    
----

This will create `target/cljs.jar`.

[[installing-from-master]]
=== Installing from master

When verifying issues it may be useful to first check that the issue has
not already been resolved in master. __Do not report issues using this
method, it's only for convenience when verifying master yourself__. Make
a checkout of the ClojureScript repository. From the root of the project
run the following:

[source,bash]
----
./script/build        
----

This will install ClojureScript into your local Maven. Make note of the
version when it scrolls by. Use this as appropriate for your tooling.
