= Running the Tests
David Nolen
2016-08-01
:type: community
:toc: macro
:icons: font

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

[[testing-the-compiler-infrastructure]]
== Testing the Compiler Infrastructure

[source,bash]
----
lein test
----

Will run the tests for the analyzer, compiler, and closure components.

[[testing-javascript-engines]]
== Testing JavaScript Engines

How to setup the important JavaScript runtimes.

[[google-v8]]
=== Google V8

http://code.google.com/p/v8/[Checkout the V8 project]. Following the
build instructions https://developers.google.com/v8/build[here]

Set the V8_HOME environment variable to the path where d8 lives.

`export V8_HOME="$HOME/v8/out/native"`

[[spidermonkey]]
=== Spidermonkey

Get the js-shell from here
http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-mozilla-central/.
Set your SPIDERMONKEY_HOME environment variable.

[[javascriptcore]]
=== JavaScriptCore

On macOS download a http://webkit.org[WebKit nightly] and put it in your
Applications folder. Update your shell profile to include the following:

[source,bash]
----
DYLD_FRAMEWORK_PATH=/Applications/WebKit.app/Contents/Frameworks/10.12/
export DYLD_FRAMEWORK_PATH
PATH=$PATH:/Applications/WebKit.app/Contents/Frameworks/10.12/JavaScriptCore.framework/Resources
----

_NOTE:_ Sub in the correct macOS version if you're not running `10.12`

[[nashorn]]
=== Nashorn

Setup the `$NASHORN_HOME` environment variable so that

`$NASHORN_HOME/jjs`

prompts a JavaScript Console. Nashorn is usually under `$JAVA_HOME/bin`,
so you can write:

`export NASHORN_HOME="$JAVA_HOME/bin/"`

[[chakracore]]
=== ChakraCore

Get ChakraCore from here
https://github.com/Microsoft/ChakraCore/releases.
Set your CHAKRACORE_HOME environment variable so that `$CHAKRACORE_HOME/ch` executes ChakraCore.

[[setting-up-dependencies]]
=== Setting up dependencies

[source,bash]
----
./script/bootstrap
----

[[running-the-tests]]
=== Running the tests

[source,bash]
----
./script/test
----

[[running-bootstrapped-clojurescript-tests]]
=== Running bootstrapped ClojureScript tests

If you have Node.js installed, you can run the bootstrapped
ClojureScript test suite (located at
`src/test/self/self_host/test.cljs`):

[source,bash]
----
./script/test-self-host
----

You can also build and run the ClojureScript compiler test suite in
bootstrapped mode within Node.js by running

[source,bash]
----
./script/test-self-parity
----

[[running-clojurescript-cli-tests]]
=== Running ClojureScript CLI (`cljs.main`) tests

You can run tests exercising the ClojureScript CLI by running

[source,bash]
----
./script/test-cli repl-env [repl-env-opts-edn]
----

where `repl-env` is any of the built-in REPL environments (`node`, `browser`, _etc._). This will be passed to `cljs.main` 's `-re` option. You can also specify a non-built-in REPL environment, but you would have to revise `script/test-cli` to include the downstream REPL environment on the classpath. You can also pass optional `repl-env-opts-edn`, which will be passed to `cljs.main` 's `-ro` option. 

[[dont-forget]]
=== Don't forget

Besides the tests it's important to make sure that the Browser REPL
hasn't accidentally been broken. Double-check using the sample found in
the repository.
