= 1.10.xxx Release
ClojureScript Team
2018-07-01
:jbake-type: post

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

## Closure Upgrades

Closure Compiler has been upgraded to v20180319.

Additionally, changes have been made so that it is possible to upgrade to the latest Google Closure Library. (The revised code is are simultaneously compatible with the latest Closure Library and the version that ClojureScript 1.10.238 depends on.)

For a complete list of updates in ClojureScript 1.10.xxx see
https://github.com/clojure/clojurescript/blob/master/changes.md#110238[Changes].

## Optimization `node_modules` Indexing

If you use `:npm-deps`, then indexing of `node_modules` should be much faster. (One test showed a 6-fold improvement in indexing speed.)

## Improvements in Testing

Several improvements have been made to ensure that the compiler test suite passes on Windows. Additionally, Graal.js, the new JavaScript engine that ships with GraalVM is included in the test suite.

## Contributors

Thanks to all of the community members who contributed to ClojureScript 1.10.xxx:

* Dieter Komendera
* Erik Assum
* Jannis Pohlmann
* Juho Teperi
* Mike Fikes
* Petter Eriksson
* Roman Scherer
