= 1.10.xxx Release
ClojureScript Team
2018-09-01
:jbake-type: post

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

## Warnings on Private Var Use

ClojureScript will now warn on private var use.

Let's say you have a funtion intended for private use in a namespace:

[source,clojure]
----
(ns foo.core)

(defn- some-impl [x]
  (inc x))
----

and you inadvertently use it from some other namespace, as in

[source,clojure]
----
(ns bar.core
 (:require [foo.core]))

(foo.core/some-impl 3)
----

The compiler will now emit a helpful diagnostic:

[source]
----
WARNING: var: foo.core/some-impl is not public
----

This is only a warning; the ClojureScript compiler continues to not prevent private var use, but now emits a new analysis warning, controllable via `:private-var-access`.

If instead var indirection is used, as in the following, no warning will be emitted:

[source, clojure]
----
(#'foo.core/some-impl 3)
----

## Function Return Type Inference

ClojureScript now infers function return types, propagating this information
to call sites.

Consider these predicates:

[source,clojure]
----
(defn finite? [x]
  (not (infinite? x)))

(defn big? [x]
  (and (pos? x)
       (finite? x)))
----

Previously, code like the following

[source,clojure]
----
(if (big? 11) 
  "hi" 
  "bye")
----

would emit defensive JavaScript that coerces the return value of `big?` 
to a Boolean by using `cljs.core.truth_`:

[source,javascript]
----
(cljs.core.truth_(cljs.user.big_QMARK_.call(null,(11)))?"hi":"bye")
----

Now, the compiler instead infers that `finite?` always returns a Boolean
value, and therefore so does `big?`, and emits more efficient code:

[source,javascript]
----
((cljs.user.big_QMARK_.call(null,(11)))?"hi":"bye")
----

With this inference, it is no longer necessary to manually add a `^boolean`
type hint to a predicate used in performance-critical code, so long as
the return value can be infered from the predicate function body.

In general, any inferred types will automatically flow from
function bodies outward, such as an inferred numeric type in the following
example:

[source,clojure]
----
(defn foo [x]
  (+ x 3))
----

If `foo` is used in a context where types are checked, as in 

[source,clojure]
----
(+ (foo 1) "a")
----

you will now see a warning that properly reflects the type:

[source]
----
WARNING: cljs.core/+, all arguments must be numbers, got [number string] instead
----

Previously, without an explcit type hint on `foo`, the compiler would produce a 
warning that indicateis a type of `any` instead of `number`.


For a complete list of updates in ClojureScript 1.10.xxx see
https://github.com/clojure/clojurescript/blob/master/changes.md#xxxxx[Changes].

## Contributors

Thanks to all of the community members who contributed to ClojureScript 1.10.xxx:

TODO: Populate this list
* Mike Fikes
