= Shared AOT Cache
Mike Fikes
2018-03-12
:jbake-type: post

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

When you compile ClojureScript code, several artifacts are produced, including JavaScript, analysis metadata, and source maps. These are cached locally, in an output subdirectory (typically “out” or “target”).

Since these artifacts are expensive to produce, it is tempting to include them in shipping library JARs. But, the artifacts depend on the compiler version as well as build-affecting compiler options (such as `:target` or `:static-fns`), so this approach is infeasible.

A new feature in ClojureScript effectively solves this problem: Compilation artifacts produced from JARs are placed in a shared cache. This means that you can comple, say, `core.async` 0.4.474 _once_.

The shared cache will be reused across different ClojureScript projects you might have on your computer. It will also be used as a source to populate your output directory if you perform a “clean” in a project and build it from scratch. This can drastically reduce the build time, as you are only compiling the source in your project proper.

Since ClojureScript itself is a typically a JAR dependency, the shared AOT cache mechanism will be—in typical Lisp metacicular fashion—applied to ClojureScript _itself_, caching artifacts produced for `cljs.core` and other namespaces that ship with ClojureScript.

This enables is a new feature of `cljs.main`: For certain use cases, like simply using it to run a script, evaluate a form with `-e`, or just fire up a REPL, `cljs.main` will use a _temporary_ output directory instead of dirtying the filesystem by creating an “out” directory where you ran `cljs.main`. The ability to use an AOT `cljs.core` makes this use case nice and zippy.

The AOT cache logic is smart enough to deal with different compiler versions, build-affecting options, and JAR names, by using that information to store artifact separately in the cache. And, while the AOT cache feature is motiviated by the notion that code in shipping JARs is immutable, it recognizes that this does not hold in the case of snapshot JARs or locally deployed JAR revisions. In those cases, the change in JAR timestamp will invalidate the cache.

By default, this feature is enabled if ClojureScript is itself a JAR dependency, and it is disabled otherwise. You can override the defaults by explicitly using a new `:aot-cache` compiler option.

Since this strategy doesn't depend on AOT artifacts being included in shipping JARS, it should be amenable to  https://clojure.org/news/2018/01/05/git-deps[Git Deps]. Perhaps that will come in a future release of ClojureScript.

Our hope is that this feature is one of those that you actually don't even think about, and that it just further helps get to to your day-to-day development!