= 1.10.891 Release
ClojureScript Team
2021-11-05 10:30:00
:jbake-type: post

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

We're happy to announce a new release of ClojureScript. If you're an existing
user of ClojureScript please read over the following release notes carefully.

## Noteworthy Changes

* Closure Compiler has been updated to `v20210808`
* Google Closure has been updated to `0.0-20211011-0726fdeb`

### Google Closure Library & goog.module

Choosing to generate JavaScript optimized for Google Closure Compiler has an
additional benefit - Google Closure Library. Even in the time of the evergreen browser,
Google Closure Library extensively tested body of code protects against the
various quirks that inevitably arise in face of many, many implementations.

The tradeoff of such a tight integration with Closure Compiler & Library is
that changes cascade into ClojureScript. For past couple few years Compiler & Library
have seen quite a bit change due to clear desire to modernize Google's JavaScript.

The most notable one has been a slow movement towards `goog.module` away from
the original `goog.require` and `goog.provide` pattern which is better suited
for REPL driven development as it effectively delivers a late bound environment
for "free".

`goog.module` adopts some of ideas and concepts from ES modules. The important
thing is that `goog.module` is *not* globally defined and must be imported into
a scope.

## Change List

For a complete list of updates in ClojureScript 1.10.891 see
https://github.com/clojure/clojurescript/blob/master/changes.md#1.10.891[Changes].

## Contributors

Thanks to all of the community members who contributed to ClojureScript 1.10.891:

* Chance Russell
