= 1.10.844 Release
ClojureScript Team
2021-04-24 10:30:00
:jbake-type: post

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

We're happy to announce a new release of ClojureScript. If you're an existing
user of ClojureScript please read over the following release notes carefully.

## Noteworthy Changes

* Closure Compiler has been updated to `v20210302`
* Closure Library has been updated to `0.0-20201211-3e6c510d`

Note that the latest Closure Library release includes breaking changes that may  
impact your code: In particular `goog.debug.Logger.Level` is has been renamed 
to `goog.Logger.Level` and the `goog.log.Level/getLogger` function now takes an 
additional argument.  Additionally, Closure namespace loading logic has been 
revised, necessitating updates to some REPLs.

## New Core Features

### Library Property Namespaces

Previously there was no disciplined way to interact with global libraries. Access 
was always via `js/foo`. ClojureScript now provide a non-clashing convention for
naming global libraries.

You can now use `goog$global.<global name>`. For example:

[source,clojure]
----
(ns my-ns.core
  (:require [goog$global.Math :refer [max]]))
----

This disciplied approach will also work for many other contexts, say a JavaScriptCore
application embedded in iOS:

[source,clojure]
----
(ns my-ns.core
  (:require [goog$global.NativeBridge :refer [bar]]))
----

Benefits of this new capability include the ability to validate via externs 
when available.

## Notable Fixes

### Accurate file name and line numbers in `cljs.test`

Instead of inaccurately inferring file name and lne numbers from the call stack
in `do-report`, they are now captured during macro-expansion based on metadata.

### `sort` and `sort-by` retain meta

This simple change makes `sort` and `sort-by` consistent with Clojure. For example,
the following evaluates to `{:a true}`:

[source,clojure]
----
(meta (sort (with-meta (range 10) {:a true})))
----

### Floating point issues with `range`

Some floating point issues were addressed for `range`, making, for example 
`(range 0 (+ 1 (/ 9)) (/ 9))` have 10 elements and `(nth (range 0 1 0.1) 6)` 
properly evaluate to `0.6`. 

### `#inst` parsing and printing, reflect proleptic Gregorian

JavaScript employs a proleptic Gregorian date system and some bugs in ClojureScript's
`#inst` support is now fixed for very old dates with respect to parsing and printing
`#inst` values.

## Performance Improvements

### Reduce code generated by destructure macro for maps

The code generated to implement map destructuring was optimized by introducing 
a shared helper to handle kw-args, reducing a portion of the Closure-optimized
output from 35 bytes down to 5, a nice savings since map destructuring is
frequently employed in code.

## Change List

For a complete list of updates in ClojureScript 1.10.844 see
https://github.com/clojure/clojurescript/blob/master/changes.md#1.10.844[Changes].

## Contributors

Thanks to all of the community members who contributed to ClojureScript 1.10.844:

* Arne Brasseur
* Eric Assum
* Hyunwoo Nam
* Matthew Huebert
* Thomas Heller
