= 1.12.42 Release
ClojureScript Team
2024-05-12 12:00:00
:jbake-type: post

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

We're happy to announce a new release of ClojureScript. If you're an existing
user of ClojureScript please read over the following release notes carefully.

This release features two significant dependency changes. First, Google Closure
Compiler has been updated to `v20250402`. This change makes Java 21 a
requirement for ClojureScript. The other significant change is that this release
now depends on the Clojure fork of Google Closure Library. Please read on for
more details about these changes.

For a complete list of fixes, changes, and enhancements to
ClojureScript see
https://github.com/clojure/clojurescript/blob/master/changes.md#1.12.42[here]

## Google Closure Compiler & Java 21

Last year we noted that updating Google Closure Compiler would mean losing Java
8 support. Google Closure now requires Java 21. From our perspective this change
doesn't seem strictly necessary, but Google is a large organization and this
change is likely to due to internal requirements which are hard to influence from
the outside. The general enthusiasm in the Clojure community about adopting more
recent Java releases hopefully softens the overall impact of this change.

So far, the burden of staying current with Google Closure has been manageable.
If for some reason that calculus changes, we could adopt the strategy we have taken
with Google Closure Library.

## Clojure's Fork of Google Closure Library

Google stopped contributing to Google Closure Library (GCL) last August. As far
as ClojureScript is concerned, the stability of GCL had declined significantly
over the past few years after a long period of stability. Google was both
trying many things with respect to their internal JavaScript strategy as
well becoming less concerned about the impact on outside consumers.

We have forked Google Closure Library and taken up maintenance. The very
first changes made were simply backing out previously commited breaking changes,
and aligning the codebase with the latest Google Closure Compiler release.

One of the biggest benefits of GCL is that it makes ClojureScript a complete
solution for writing ClojureScript for a variety of JavaScript contexts, not
limited to the browser. These days, ClojureScript integrates well with the wider
JavaScript ecosystem these days, but ClojureScript always provided a solid of set of tools
out of the box as reliable as the standard library. That was absolutely true from
2011-2019 when GCL rigorously avoided breaking changes.

We are working on restoring that rock solid stability. With this release, you'll find
that quite a few fine old ClojureScript libraries work again today as well as
they did 14 years ago.

ClojureScript is not just for rich web applications. Many websites need rich
DOM manipulation, robust internationalization, and compelling interactivity on
a website without going to a framework. In these cases ClojureScript
generates surprisingly compact output compared to the JavaScript alternatives.d

Give it a try!