= 1.12.38 Release
ClojureScript Team
2024-05-12 12:00:00
:jbake-type: post

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

We're happy to announce a new release of ClojureScript. If you're an existing
user of ClojureScript please read over the following release notes carefully.

This release features two significant dependency changes. First, Google Closure
Compiler has been updated to `v20250402`. This change makes Java 21 a
requirement for ClojureScript. The other significant change is that this release
now depends on the Clojure fork of Google Closure Library. Please read on for
more details about these changes.

For a complete list of fixes, changes, and enhancements to
ClojureScript see
https://github.com/clojure/clojurescript/blob/master/changes.md#1.12.38[here]

## Google Closure Compiler & Java 21

Last year we noted that updating Google Closure Compiler would mean losing Java
8 support. Google Closure now requires Java 21. From our perspective this change
doesn't seem strictly necessary, but Google is a large organization and this
change is likely to due to internal requirements which are hard to influence from
the outside. The general enthusiasm in the Clojure community about adopting more
recent Java releases hopefully softens the overall impact of this change.

So far, the burden of staying current with Google Closure has been manageable.
If some reason that calculus changes, we could adopt the strategy we have taken
with Google Closure Library.

## Clojure's Fork of Google Closure Library

Google stopped contributing to Google Closure Library (GCL) last August. As far
as ClojureScript is concerned, the stability of GCL had declined significantly
over the past few years after a long period of stability. Google was clearly
trying many things with respect to their internal JavaScript strategy and it
showed. Google ending GCL development removes a consistent source of unexpected
surprises between releases.

We have forked Google Closure Library and taken up maintenance. The very
first changes made were simply backing out previously commited breaking changes,
and aligning the codebase with the latest Google Closure Compiler release.

But why stick with an "aging" JavaScript library? Didn't Google themselves claim
GCL was old-fashioned? Unfortunately, for optics, Google avoided enumerating the
now well-understood costs associated with mainstream JavaScript development
practices. To be perfectly fair to JavaScript, these problems have permeated
the software industry for years and they are cultural, not technical in nature.

One of the biggest benefits of GCL is that it makes ClojureScript a complete
solution for writing ClojureScript for a variety of JavaScript contexts,
not limited to the browser. You don't need to deal with Node modules and
dependencies, build tools, build plugins, and other various flavors of the month
to add some interactivity to a website. It rarely matter hows old a dependency
is, take for example `domina`. Sure it generates a bunch of style warning from
the ClojureScript compiler, but it compiles. If not for a Google Closure Library
change you could use the entire API today.

## Contributors

Thanks to all of the community members who contributed to
ClojureScript 1.12.38:

* Michiel Borkent
* Mike Fikes