= 1.12.35 Release
ClojureScript Team
2024-04-24 12:00:00
:jbake-type: post

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

We're happy to announce a new release of ClojureScript. If you're an
existing user of ClojureScript please read over the following release
notes carefully.

This release features two significant dependency changes. First,
Google Closure Compiler has been updated to `v20250402`. This change
makes Java 21 a requirement for ClojureScript. The other signficant
change is that this release now depends on the Clojure fork of Google
Closure Library. More on that later.

For a complete list of fixes, changes, and enhancements to
ClojureScript see
https://github.com/clojure/clojurescript/blob/master/changes.md#1.12.35[here]

## Google Closure Compiler & Java 21

Last year we noted that updating Google Closure Compiler would mean
losing Java 8 support. Google Closure now requires Java 21.

## Clojure's Fork of Google Closure Library

Google stopped contributing to Google Closure Library (GCL) last
August. As far as ClojureScript was concerned, the stability of GCL
had declined significantly over the past 5 years with an increasing
amount of churn as Google sorted out their internal JavaScript
strategy. Google stopping GCL development removes a consistent source
of unexpected surprises between releases.

We have forked Google Closure Library and have taken up maintenance.
The very first changes made were simply backing out breaking changes
aligning the codebase with the latest Google Closure Compiler
release.

## Contributors

Thanks to all of the community members who contributed to
ClojureScript 1.12.35:

* Michiel Borkent
* Mike Fikes