= JavaScript Modules (Alpha)
David Nolen
2017-01-22
:type: guides
:toc: macro
:icons: font

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

This page documents how to mix modern JavaScript source files seamlessly into
an existing ClojureScript project. The features documented should be considered
of alpha quality and subject to change.

[[motivation]]
== Motivation

When ClojureScript was initially released, compilation to JavaScript was still a
novelty and source transformation beyond minification was rare. More recently,
source to source compilation of JavaScript has become increasingly popular,
whether embedded HTML as with React JSX, or the new ECMAScript standards that
address many of JavaScript's old weaknesses. But integrating these new kinds of
source files required deferring to JavaScript build tools which still lack
the more advanced features of the Google Closure compiler like dead code
elimination and precise code splitting.

Fortunately Google Closure has not only kept abreast of many of the various
enhancements to the JavaScript language, they've also provided transformation
from the various popular JavaScript module formats (CommonJS, AMD, ES6) into the
Google Closure namespace convention. ClojureScript now exposes all of this
functionality and with the help of Java 8's Nashorn JavaScript engine can
provide even the most cutting edge JavaScript source transforms with ease.

[[pre-requisitess]]
== Pre-requisites

This guide assumes you have the latest release of JDK 8 as well as Leiningen
installed. The instructions are easily adaptable to Boot or Maven. You should
also have the latest stable version of Node.js installed for the REPL portion of
the guide.

[[es6]]
== ES6

First let's see how ES6 source files can be a part of your build:

----
mkdir -p hello-es6
cd hello-es6
touch project.clj
----

Edit the `project.clj` file to look like the following:

[source,clojure]
----
(defproject hello-es6 "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.9.0-alpha13"]
                 [org.clojure/clojurescript "1.9.NNN"]]
  :jvm-opts ^:replace ["-Xmx1g" "-server"])
----

Create a watch script:

----
touch watch.clj
----

Edit it to look like the following:

[source,clojure]
----
(require '[cljs.build.api :as b])

(b/watch "src"
  {:output-to    "out/main.js"
   :output-dir   "out"
   :main         'hello-es6.core
   :target       :nodejs
   :foreign-libs [{:file "src"
                   :module-type :es6}
   :verbose      true])
----

Then create the main namespace:

----
mkdir -p src/hello_es6
touch src/hello_es6/core.cljs
----

Edit this file to look like the following:

[source,clojure]
----
(ns hello-es6.core
  (:require [js.hello :as hello]))
----

Now let's write some JavaScript:

----
mkdir -p src/js/hello.js
----

Edit this file to look like the following:

[source,javascript]
----
export let sayHello = function() {
    console.log("Hello, world!");
};
----

Let's check that our watch script works:

----
lein trampoline run -m clojure.main watch.clj
----

[[REPL]]
== REPL

[[Babel]]
== Babel

Download babel.min.js into your project directory:

----
curl -O https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.18.1/babel.min.js
----

Change your `watch.clj` to look like the following:

[source,clojure]
----
(require '[cljs.build.api :as b])
(require '[cljs.closure :as closure])

(b/watch "src"
  {:output-to    "out/main.js"
   :output-dir   "out"
   :main         'hello-es6.core
   :target       :nodejs
   :foreign-libs [{:file "src"
                   :module-type :es6}
   :verbose      true])
----
