= Quick Start
David Nolen
2016-07-29
:type: guides
:toc: macro
:icons: font

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

[[quick-start-toc]]
toc::[]

If you are using OS X or Linux the only dependencies required for this tutorial
are an installation of https://clojure.org/guides/getting_started[Clojure]. On
Windows you will need
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[Java
8] and the
https://github.com/clojure/clojurescript/releases/download/r1.9.473/cljs.jar[standalone
ClojureScript JAR].

[[clojurescript-compiler]]
=== ClojureScript Compiler

Create a directory `hello_world` then from _inside_ the `hello_world` directory:

[source,bash]
----
mkdir -p src/hello_world; touch src/hello_world/core.cljs
----

On Windows:

[source,bash]
----
md src\hello_world & type nul >>core.cljs & move core.cljs src\hello_world
----

If you are on Linux or OS X create a `deps.edn` file with the following contents:

[source,clojure]
----
{:deps {org.clojure/clojurescript {:mvn/version "1.10.104"}}}
----

If you are on Windows simply copy `cljs.jar` into this directory.

In your favorite text editor edit the `src/hello_world/core.cljs` to
look like the following:

[source,clojure]
----
(ns hello-world.core)

(println "Hello world!")
----

First we declare our namespace. This namespace must correspond to the location
of the source file. We then print the famous message.

Now that we have a simple program, let's build and run some ClojureScript:

[source,bash]
----
clj -m cljs.main -c hello-world.core -r
----

On Windows:

[source,bash]
----
java -cp "cljs.jar;src" -m cljs.main -c hello-world.core -r
----

Your default web browser will open to a page that looks like the following:

After a couple of seconds you will see `Hello world!` print at the terminal and
you will be given a REPL prompt.

Change your `src/hello_world/core.cljs` source file to look like the
following:

[source,clojure]
----
(ns hello-world.core)

(println "Hello world!")

;; ADDED
(defn foo [a b]
  (+ a b))
----

At the REPL prompt, recompile and reload your namespace by evaluating
`(require '[hello-world.core :as hello] :reload)`. Try evaluating
`(hello/foo 2 3)`, you should get the result `5`.

Lets make a mistake. Try evaluating `(ffirst [1])`. You should get a
source mapped stack trace pointing at ClojureScript source locations not
JavaScript ones. This makes debugging a lot nicer.

[[production-builds]]
== Production Builds

You may have noticed the `out` directory which contains all of the compiled
JavaScript, about 6 1/2 megabytes worth. This may seem unweildy but fortunately
the ClojureScript compiler generates output optimized for the Google Closure
Compiler. The Google Closure Compiler performs many optimizations, but the most
significant for browser-based clients are minification and dead code
elimination.

Let's remove the dev time REPL bits from `src/hello_world/core.cljs`:

[source,clojure]
----
(ns hello-world.core)

(println "Hello world!")
----

Let's create a release build:

[source,clojure]
----
clj -m cljs.main -O advanced -c hello-world.core
----

On Windows:

[source,bash]
----
java -cp "cljs.jar;src" -m cljs.main -O advanced -c hello-world.core
----

This process will take significantly longer which is why we don't use
this compilation mode for development.

Examine `out/main.js`, the file size should be around 90K. If you zip
this file you'll see that it's around 20K. This is significantly smaller
than a jQuery dependency yet when using ClojureScript you have implicit
dependencies on the entire ClojureScript standard library (10KLOC) and
the Google Closure Library (300KLOC). You can thank dead code
elimination.

You can test that this file still works by running the built in webserver:

[source,bash]
----
clj -m cljs.main -s
----

On Windows:

[source,bash]
----
java -cp "cljs.jar;src" -m cljs.main -s
----

Since this not a REPL, a browser window will not be automatically opened.
Navigate to http://localhost:9000 using your favorite browser. Check the
JavaScript Console, you should see `Hello world!` printed.

This server gzips JavaScript. Check your browser network tab and you should be
able to confirm that the total JavaScript payload is now around 20K.

[[running-clojurescript-on-node.js]]
== Running ClojureScript on Node.js

First install Node.js. For instructions on installing Node.js, see the
https://github.com/nodejs/node/blob/master/README.md[Node.js wiki]. Only
the current stable versions of Node.js (>= `0.12.X`) are supported at
this time.

Node.js has great source mapping support, in order to enable it just
install `source-map-support`:

[source,bash]
----
npm install source-map-support
----

Let's build your Node project:

[source,bash]
----
clj -m cljs.main -t node -o main.js -c hello-world.core
----

On Windows:

[source,bash]
----
java -cp "cljs.jar;src" -m cljs.main -t node -o main.js -c hello-world.core
----

You can run your file with:

[source,bash]
----
node main.js
----

[NOTE]
====
**Note**: Under Node.js there is little reason to use advanced
optimizations. While advanced optimizations does apply performance
related optimizations, these are now largely obviated by optimizations
present in modern JavaScript virtual machines like V8, SpiderMonkey, and
JavaScriptCore. For Node.js, `:simple` or `:none` optimizations suffice
and using them removes the need for extra steps like supplying an
externs file.
====

[[node.js-repl]]
=== Node.js REPL

Running a Node.js REPL is similar to running a browser REPL.
Let's start the REPL:

[source,bash]
----
clj -m cljs.main -re node
----

On Windows:

[source,bash]
----
java -cp "cljs.jar;src" -m cljs.main -re node
----

All the previously described REPL interactions for the browser should
work.

[[dependencies]]
== Dependencies

ClojureScript supports a wide variety of options for including
ClojureScript and JavaScript dependencies (see
<<xref/../../../reference/dependencies#,Dependencies>>
for details).

http://facebook.github.io/react/[React] is a popular dependency for
ClojureScript projects. http://cljsjs.github.io[CLJSJS] provides a
https://github.com/cljsjs/packages/tree/master/react[bundled version].
Let's see how to include it.

Modify your `deps.edn` file:

[source,clojure]
----
{:deps {org.clojure/clojurescript {:mvn/version "1.10.109"}
        cljsjs/react-dom {:mvn/version "16.2.0-3"}}}
----

Let's edit our simple program to look like the following so that React
is properly required:

[source,clojure]
----
(ns hello-world.core
  (:require react-dom))

(.render js/ReactDOM
  (.createElement js/React "h2" nil "Hello, React!")
  (.getElementById js/document "app"))
----

Let's build and run:

[source,bash]
----
clj -m cljs.main -c hello-world.core -r
----

When the browser launches you should momentarily see the default page
which will then be quickly replaced by a `h2` tag containing `Hello React!`.