= The Reader
Henry Widd
2021-05-25
:type: guides
:toc: macro
:icons: font

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

The behaviour of Clojurescript's reader is mostly the same as the https://clojure.org/reference/reader[Clojure Reader]
but with notable differences with respect to tagged literals.

[[tagged_literals]]
== Tagged Literals

Tagged Literals allow users to extend the reader. See https://Clojure.org/reference/reader#tagged_literals[the Clojure guide]
on tagged literals for an introduction.

In order to read custom tagged literals in Clojurescript source, namespaced symbols are associated with reader 
functions in a data_readers.cljc file. See info on data_readers.clj (note the suffix difference) in the Tagged Literals link above for 
details.

== Reader functions 

There is a fundamental difference between reader functions targeting Clojure vs Clojurescript. 
Separate from language target, we also need to consider the context in which reader functions execute,
which can be:

* in Clojure during Clojurescript compilation 
* in a js runtime when reading EDN 
* self-hosted Clojurescript compiler read.

=== Targeting Clojurescript

Reader function should return a form which represents valid Clojurescript. This is similar to how macros work.

[source,Clojure]
----
(defn my-cljs-targeting-reader-fn [form]
  `(.foo ~form)) 
----

=== Targeting Clojure

Unlike Clojurescript, a reader function should return a result which will not be read/compiled further. Any evaluation of the form should happen in the 
reader function.

[source,Clojure]
----
(defn my-clj-targeting-reader-fn [form]
  (.foo form)) 

----
 
== Reader function execution

A reader function targeting just Clojure is just a regular Clojure function.

A symbol in data_readers.cljc referring to a reader function targeting Clojurescript should resolve to:
* a Clojure function that runs during Clojurescript compilation
* potentially also a Clojurescript function that will run is a js runtime when self-hosted, and/or 
when reading edn using `cljs.reader`. 

These functions may appear unconditionally in a .cljc file if the code is the same for both.

== Cross platform Tagged Literals (ie a literal to target both Clojure and Clojurescript)

These are not currently supported as the Clojurescript compiler does not support conditional read in 
data_readers.cljc, despite its suffix.  
https://Clojure.atlassian.net/jira/software/c/projects/CLJS/issues/CLJS-3294 is the issue relating to this
bug. Note that the Clojure compiler reads both data_readers.clj and data_readers.cljc (and unlike the 
Clojurescript compiler does respect conditional read) so to avoid confusion just use data_readers.cljc when
defining your own reader literals.

As a workaround, it is possible to have 2 data_readers.cljc files: one pointing to a Clojure-targeting reader and one pointing to a Clojurescript-targeting reader. 
For Clojurescript compilation, include only the Clojurescript-targeting one (via classpath) and for Clojure, again restrict the classpath to just the Clojure-targeting file. 