= Emacs and Inferior Clojure Interaction Mode
David Nolen
2016-08-02
:type: tools
:toc: macro
:icons: font

> **NOTE**: This guide requires ClojureScript 1.10.238 or later and assumes
> familiarity with the <<xref/../../guides/quick-start#,Quick Start>>.

Assuming you already have `clojure-mode`, run `M-x package-list-packages` and
install `inf-clojure`. If you are using Emacs on OS X be sure to install
`exec-path-from-shell` so that the Node.js REPL will work correctly. If you need
`exec-path-from-shell` make sure to follow the
https://github.com/purcell/exec-path-from-shell#usage[Usage] instructions.

Edit your `.emacs` or `init.el` and add a function like the following if you are
using the JAR in your current directory:

[source,clojure]
----
(defun cljs-node-repl ()
  (interactive)
  (inf-clojure "clj -m cljs.main -co build.edn -re node -r"))
----

Open your ClojureScript file and run `M-x cljs-node-repl`. You'll get a new
buffer with the REPL. Switch back to your file and run `M-x
inf-clojure-minor-mode`. `C-c C-l` will load the file. `C-c Meta-n` will switch
your namespace. If you place your cursor at the end of a s-expression, `C-x C-e`
will evaluate that expression. `C-c C-v` will show the docs. `C-c C-s` will show
the source. `C-c <return>` will macroexpand. Refer to
https://github.com/clojure-emacs/inf-clojure[inf-clojure] for more
documentation.
